### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by Unknwon** [drone/docs#110]
Hi, this site looks awesome!

I wonder what is the license for this repository? Because I want to use for my site as well.

Thanks!

**Comment by gtaylor** [comment]
It's *probably* Apache 2.0, but I filed a PR (#113) to make this 100% clear (assuming I guessed correctly).

**Comment by Unknwon** [comment]
:+1:

**Comment by bradrydzewski** [comment]
@Unknwon since this repository is mostly content and design, I added a creative common license. Hope that helps :)

**Comment by Unknwon** [comment]
:100: Thanks for the good design!
