### ISSUE TITLE
How do I add a new user

### ISSUE THREAD

**Issue by cimm** [drone/docs#117]
I have Drone up and running and would like to invite a second user but... how? There is a "People" section when I click on my avatar where I can add a user, the placeholder text says _"ie octocat"_ but no indication on what is expected here.

Is this a name I can choose? If so, how does Drone know who to map it to, there is no email field? Maybe it's a Gitlab or Github account? If it so, does the account need access to the source repository?

Tried with a Github account (username in Drone the same as the Github account) whom I gave access to the source repo but that person can't log in.

Can't find anything in the documentation or on Google.

**Comment by bradrydzewski** [comment]
It is the github username. We have a support channel for these type of questions at https://gitter.I'm/drone/drone

**Comment by cimm** [comment]
Great, thank you and sorry for using the wrong support channel.
