### ISSUE TITLE
Bitbucket merge request "partially" supported - unexplained

### ISSUE THREAD

**Issue by jsonfry** [drone/docs#119]
The partial support for Bitbucket merge requests is unexplained. I found this in the git history before the supports table was split into different files:

> *partially* - Drone can fetch merge requests direct from source repository, from BitBucket, but if user who activates drone on target repo has no access to source repo, git clone fails

Is this still correct? I guess this means that pull requests between branches in the same repo works fine?

**Comment by jsonfry** [comment]
I can do a PR to add this back in if you like

**Comment by gtaylor** [comment]
Will have to defer to @bradrydzewski on this one. We use Bitbucket, but don't use PRs in our workflow. I haven't ever looked at this.

**Comment by jsonfry** [comment]
He'll probably think I'm being a pain then given that he's just told me they aren't supported... https://github.com/drone/drone/issues/1549

**Comment by gtaylor** [comment]
Ah, so sounds like we should avoid confusion entirely and say "are not supported" instead of "partially". As far as the users are concerned, they don't work.

Unless Brad chimes in otherwise, I'll accept a PR for this change.

**Comment by jsonfry** [comment]
Well, I think are building if you manually enable the right hooks on bb, but maybe that's unintended hackery...
