### ISSUE TITLE
Wrong URL in Cancel a Job

### ISSUE THREAD

**Issue by MetalMatze** [drone/docs#126]
I think the path in the docs is wrong.

Docs: `/api/repos/MetalMatze/drone-test/logs/10/1`
Actual: `/api/repos/MetalMatze/drone-test/builds/10/1`

It should be `builds` not `logs`.

**Comment by gtaylor** [comment]
Would you mind sending a PR for this?

**Comment by MetalMatze** [comment]
I can do that tomorrow. I've shutdown my computer right now.

**Comment by MetalMatze** [comment]
This was merged.
