### ISSUE TITLE
Default User/Password

### ISSUE THREAD

**Issue by smith64fx** [drone/docs#142]
After installing drone with Docker, I can open the web interface.

But where the hell can I find the default username and password???

**Comment by tboerger** [comment]
There is no default username/password. Drone doesn't have any authentication integrated, it's all up to your configured remote driver, e.g. GitHub/Gitlab/Gogs/Bitbucket.

**Comment by bradrydzewski** [comment]
drone uses oauth2 which means it delegates login to GitHub, GitLab and Bitbucket. If you are using Gogs you enter your Gogs username and password.
