### ISSUE TITLE
Document that the CLI tool is deprecated and why

### ISSUE THREAD

**Issue by ches** [drone/docs#143]
The drone-cli repo has "DEPRECATED" in its description, but no explanation in the README or on the [CLI doc page][1] as to why this is the case or what users should expect for now or the future. Issues have been disabled on the drone-cli repo so I guess this is the best place to raise this as a problem.

[1]: http://readme.drone.io/devs/cli/

**Comment by bradrydzewski** [comment]
drone-cli has been merged into the main drone/drone repository for the upcoming 0.5 release. The 0.4 cli is frozen in anticipation for the 0.5 release

**Comment by bradrydzewski** [comment]
note I updated the project description to `DEPRECATED and moved into drone/drone` with a link to the main repository

**Comment by ches** [comment]
Thanks, that helps.
