### ISSUE TITLE
403 when trying to download drone CLI on Windows

### ISSUE THREAD

**Issue by jhasse** [drone/docs#148]
The link http://downloads.drone.io/release/windows/amd64/drone.zip in the docs https://github.com/drone/docs/blob/release/0.5/content/reference/cli/overview.md#install-on-windows results in 403 Forbidden for me.

(I'm trying to test the Windows install instructions, see #145)

**Comment by gtaylor** [comment]
This will start functioning when 0.5 is set up to auto-build. It's still a bit too raw for that.

**Comment by jhasse** [comment]
Is there an issue for auto-builds that I can subscribe to? I want to try the CLI on Windows ASAP :)
