### ISSUE TITLE
Bitbucket server docs are not entirely clear 

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#159]
Moved from https://github.com/drone/drone/issues/1734

It may as well be Atlassian's fault that they made the process so unnecessary complex, but at this point it's very hard to understand how to configure bitbucket server to work with drone.
- http://readme.drone.io/0.5/installation/services/bitbucet_server/ (note `bitbucet` too)

I managed to get to the following screen:

![image](https://cloud.githubusercontent.com/assets/89186/17145136/040f68c0-5351-11e6-890f-0ec08ac456a5.png)

And it's not clear how to generate the keys and what URLs to use. Step by step guide for making it work would be great.

cc @josmo

**Comment by bradrydzewski** [comment]
cc @bobrik

**Comment by josmo** [comment]
@bobrik Sadly Atlassian doesn't really make it easy.  however I'll try to update the docs to make it more clean and have a step by step guide on it.  I'm doing a new setup later today so I'll see about updating the docs then.

**Comment by appleboy** [comment]
ref: https://github.com/drone/docs/pull/169

**Comment by tphoney** [comment]
https://docs.drone.io/ has moved on, and bitbucket server setup is much clearer.
