### ISSUE TITLE
Chicken and egg with Atlassian Stash

### ISSUE THREAD

**Issue by travi** [drone/docs#172]
I'm not sure if it would be a problem with our version of Bitbucket Server/Stash not being supported, but I've run into a problem when trying to get drone connected as an app. We are on Stash v3.11.4, which is before they changed the naming to Bitbucket Server, but I see Stash mentioned in your docs. Also, I'm trying to use `drone/drone:0.4` as mentioned in the docs.

The issue is related to the fact that Stash tries to verify the url of the application before it allows it to be added. Without successully adding the application within Stash, I don't have valid credentials to pass to `REMOTE_CONFIG`. However, drone is failing to start without the `REMOTE_CONFIG` being populated. I've tried various levels of partial config, including the following.
```
time="2016-08-16T00:12:37Z" level=info msg="using remote config REMOTE_CONFIG=https://stash.ourcompany.net?open=false&git_username=drone&git_password=xxx&consumer_key=foo&consumer_rsa=bar" 
time="2016-08-16T00:12:37Z" level=fatal msg="remote configuraiton not found" 
```

Do you have a suggestion for getting the drone server to start so that Stash can verify that it is alive and add it as an app?

**Comment by gtaylor** [comment]
Questions like this are best handled on Discourse or in the Gitter room. If you figure this out for 0.5 and want to submit a PR, come back on over and do it against the release/0.5 branch.

**Comment by appleboy** [comment]
@travi Please try out drone `0.5` version. It is working for me.
