### ISSUE TITLE
There are two different versions of the online documentation for version 0.5

### ISSUE THREAD

**Issue by francoishill** [drone/docs#192]
This seems to be the "older" docs: http://readme.drone.io/0.5/manage/server/
Guess then this is the "newer"? http://readme.drone.io/0.5/installation/server/

In the second link if we go to the [Agents](http://readme.drone.io/0.5/installation/agents/) it uses WebSockets (prefixed with `ws://` instead of `http://`) for the `DRONE_SERVER` variable.

This could be very misleading since the current docker image for 0.5 does not work with the "older" docs.

**Comment by appleboy** [comment]
I make new PR https://github.com/drone/docs/pull/194 to fix `DRONE_SERVER` variable.

**Comment by tboerger** [comment]
> In the second link if we go to the Agents it uses WebSockets (prefixed with ws:// instead of http://) for the DRONE_SERVER variable.


Why should that be misleading? That is totally correct for websockets.

**Comment by francoishill** [comment]
Thanks @appleboy for the fix.
@tboerger, the problem was that the two docs (both for version 0.5) showed different settings. That is now before the fix of @appleboy
