### ISSUE TITLE
translate usage/getting-started to russian

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#205]
@v-kiptilov you mentioned an interest in helping translate the docs to russian. The docs are still a work in progress, so let's plan to tackle them in sections. This is the first section ready to translate:

https://github.com/drone/docs/blob/master/content/usage/getting_help.ru.md
https://github.com/drone/docs/blob/master/content/usage/getting_started.ru.md

**Comment by v-kiptilov** [comment]
@bradrydzewski Thanks for the info ;-) I'll tackle those first!

**Comment by tphoney** [comment]
Hey @fcoedno we are not currently accepting pr's for translation, as our documentation is changing rapidly, we will be tackling our documentation later in the year, and will re-visit this decision then.
