### ISSUE TITLE
translate usage/getting-started to spanish

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#206]
@yamilurbina @ma0c you both mentioned an interest in helping translate the docs to spanish. The docs are still a work in progress, so let's plan to tackle them in sections. This is the first section ready to translate:

https://github.com/drone/docs/blob/master/content/usage/getting_help.es.md
https://github.com/drone/docs/blob/master/content/usage/getting_started.es.md

Let me know if either of you are still interested. Thanks!

**Comment by yamilurbina** [comment]
@bradrydzewski count me in!

**Comment by ma0c** [comment]
I'm on it too

**Comment by bradrydzewski** [comment]
awesome, thanks!

I've also split out all the strings into a separate file
https://github.com/drone/docs/blob/master/i18n/es.yaml

**Comment by ma0c** [comment]
Sure, I already create a pull request with two first sections translated, must remove the yaml spec from the code example don't know why

**Comment by ma0c** [comment]
Also translated i18n/es.yml on https://github.com/contraslash/drone-docs/commit/417a0efe0bb380c87af1086039ed9d5e88149ea3 Waiting to approve first pull request.

Just let me know when other sections will be ready to translate

Have a good day

**Comment by tphoney** [comment]
We are not currently accepting pr's for translation, as our documentation is changing rapidly, we will be tackling our documentation later in the year, and will re-visit this decision then.
