### ISSUE TITLE
translate usage/getting-started to chinese

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#207]
@renothing @qinwf you both mentioned an interest in helping translate the docs to chinese. The docs are still a work in progress, so let's plan to tackle them in sections. This is the first section ready to translate:

https://github.com/drone/docs/blob/master/content/usage/getting_help.zh.md
https://github.com/drone/docs/blob/master/content/usage/getting_started.zh.md

Let me know if either of you are still interested. Thanks!

**Comment by renothing** [comment]
yes, I will start it in 2 days

**Comment by qinwf** [comment]
Great!

**Comment by qinwf** [comment]
@renothing I created a gitter room for us to communicate.

https://gitter.im/drone-cn-doc/Lobby

**Comment by bradrydzewski** [comment]
thanks! I've also started putting all strings into separate files for easy translation https://github.com/drone/docs/blob/master/i18n/zh.yaml

**Comment by tphoney** [comment]
We are not currently accepting pr's for translation, as our documentation is changing rapidly, we will be tackling our documentation later in the year, and will re-visit this decision then.
