### ISSUE TITLE
Bitbucket Server requires webhooks addon installed/enabled

### ISSUE THREAD

**Issue by flaccid** [drone/docs#223]
PR required. In order to create a webhook for a repo when using bitbucketserver, this addon needs to be installed and enabled, https://marketplace.atlassian.com/plugins/com.atlassian.stash.plugin.stash-web-post-receive-hooks-plugin/server/overview.

We should ensure to include this information in http://docs.drone.io/install-for-bitbucket-server/ as a prerequisite.

**Comment by tphoney** [comment]
> This plugin is now obsolete and unsupported:
> 
> As of Bitbucket Server 5.4 webhooks is a bundled feature rendering this plugin obsolete. For more details see: https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html
