### ISSUE TITLE
Improve plugin secret mapping docs

### ISSUE THREAD

**Issue by tonglil** [drone/docs#249]
Add to the docs:

How parameters are mapped from config to env vars: https://github.com/drone/drone-plugin-starter#parameters

How secrets are mapped from config to env vars: https://github.com/drone/drone-plugin-starter#secrets

 ```pipeline:
  step:
    image: x/y
    username: x             -> PLUGIN_USERNAME
    secret: [docker_secret] -> DOCKER_SECRET
```

 ```pipeline:
  step:
    image: x/y
    username: x               -> PLUGIN_USERNAME
    secret:
      - source: docker_secret
        target: my_var        -> MY_VAR
```

**Comment by tphoney** [comment]
These are now documented in a more clear way.
