### ISSUE TITLE
Make it clear readme.drone.io is for 0.5

### ISSUE THREAD

**Issue by tonglil** [drone/docs#257]
Add to the index page that the documentation applies to Drone 0.5.

This can help clarify the difference between 0.5 and latest.

(I'm not sure how to update http://readme.drone.io/).

**Comment by dolanor** [comment]
From what I've found, it seems readme.drone.io version lives in the https://github.com/drone/docs/tree/release/0.5 branch.

Right now I have trouble with my company to tell them where to find documentation as readme.drone.io shows up most of the time.

For more clarity, I would remove the readme.drone.io website altogether, and put its content under docs.drone.io/v0.5 for example.

What do you think?

**Comment by tboerger** [comment]
Since drone 0.5 reached EOL the docs can be entirely removed from the website :)

**Comment by tonglil** [comment]
@bradrydzewski would have to do that right?
I think it is a good idea to preserve 0.5 docs at least somewhere (I know that having the 0.4 docs really helped us while we were still migrating to 0.8).

**Comment by tboerger** [comment]
Yeah this needs to be done by @bradrydzewski

**Comment by SAprelov** [comment]
@bradrydzewski Aaaaand?)

**Comment by tboerger** [comment]
Currently readme.drone.io is used to temporary document the upcoming next release, after that it will be dropped.
