### ISSUE TITLE
Add pipeline when conditions

### ISSUE THREAD

**Issue by tonglil** [drone/docs#258]
This seems cool: https://discourse.drone.io/t/how-make-the-tests-run-faster/696/6

I cannot find documentation, should add to either
- http://docs.drone.io/conditional-steps/
- http://docs.drone.io/pipelines/

**Comment by bradrydzewski** [comment]
we currently mention it here http://docs.drone.io/hooks/#skip-branches

**Comment by tonglil** [comment]
Thanks, I guess I wasn't looking hard enough.
It looked so closely like conditions that I didn't expect it to be under webhooks.
I am open to hearing more data points.
