### ISSUE TITLE
Document ngrok, local testing on laptop

### ISSUE THREAD

**Issue by mgeisler** [drone/docs#285]
I wanted to see if I could setup Drone on my laptop to get a feel for the system. I found http://docs.drone.io/installation/ and tried to follow the instructions there.

The instructions are not very precise and assumes a lot of familiarity with docker-compose. I had heard of docker-compose in the abstract, but here I needed to look at the help to figure out that I need to name the config file `docker-compose.yaml`. I've created #283 to improve this.

Actually running `docker-compose up` doesn't work then. You get lots of errors about undefined variables. So I kept reading and saw that the rest of the page slowly "patches" the configuration to get it nearer a working state (but doesn't actually end up giving me a working configuration).

Next confusing point was the integration with version control providers. Sure, I thought, it's nice if I can configure Drone to checkout my GitHub repositories. It's not clear that the provider is really used as an OAuth provider — #284 tries to address this.

These were some initial stumbling blocks I ran into. My next question is if it's even possible to run Drone on a laptop for testing purposes. The use of OAuth and the rediction URL makes me wonder this — I would set it to `localhost/authorize`, but will that work?

The lack of confidence is a problem — ideally, the installation guide would be a step-by-step guide that quickly shows me how to get Drone running on my laptop. _If_ registration with third parties is absolutely necessary, then this should be shown in a step-by-step way too.

Right now, the installation instructions seem like a sketch at best. It might be that they really are just a sketch and that there are plans for expanding them. If that's the case, please write a note at the top saying so :-)

**Comment by mgeisler** [comment]
Tested this: creating a new "application" by going to https://github.com/settings/applications/new (as suggested in #284) and setting the redirect to `http://localhost` seems to work on my laptop.

**Comment by tboerger** [comment]
The drone server is not intended for running on a local laptop as it have to listen for webhooks from the remote driver like github. It needs some workarounds to get it working locally. For developers who wants to test their stuff before a pull request there is the drone cli with the exec command which executes the pipeline locally comparable to the server.

**Comment by mgeisler** [comment]
Hi Thomas, thanks for the reply and thanks for looking at the PRs!

It makes sense to me that the production CI master will eventually run on a place that is accessible from GitHub so the web hooks can reach it. However, for testing out Drone, I was hoping that I could still easily get something up an running without exposing it to the Internet. I would of course trigger builds manually (or have Drone poll the remote repository) since the system would be behind a NAT to start with.

I've done that with BuildBot and Jenkins in the past. Is it also possible with Drone? Or do I need to spin up some VMs somewhere with publicly accessible IPs before I can I can properly test Drone?

If I have to spin up a VM somewhere, my immediate concern is what information Drone will expose to others -- how do I make sure the web interface is locked down properly? I don't want to suddenly have a list of my private repositories visible to the world.

I have of course found http://docs.drone.io/user-registration/ and I see it talks about a `drone` CLI tool. However, I'm still in the middle of the installation instructions at this point and do not have any `drone` CLI tool installed :-) In other words, the should be a prominent link to http://docs.drone.io/cli-installation/ somewhere in the installation guide and also on the page that that talks about user management.

Running a test server on a laptop or inside a private network removes these concerns.

**Comment by mgeisler** [comment]
Feel free to close this issue if it's not helpful. I guess what I'm asking for is for the Drone project to consider

* What state do you expect the user to be in after reading the installation overview? Should I have a local Drone server up and running? If so, I believe the document needs more detailed step-by-step instructions.

**Comment by tboerger** [comment]
We always welcome pull requests that improves the documentation to make it better understandable.

If you want to try it behind a firewall you have to use some kind of tunnel like ngrok which can be accessed by github since drone doesn't provide any polling, the builds are always triggered by the Scm.

To build something locally you can also use alternatives like gitea, gogs or Gitlab.

**Comment by bradrydzewski** [comment]
I am going to rename this issue, because the default docker-compose file works out of the box on a server (the intended installation target). We have a placeholder in the documentation for ngrok, which is the recommended way to test drone locally on your laptop. We would accept a PR to document ngrok usage.

Placeholder page http://docs.drone.io/setup-with-ngrok/

**Comment by mgeisler** [comment]
Thanks Brad, makes a lot of sense to rename the issue!

My wish is to see something which makes it possible for me to get a test system up and running in perhaps half an hour.

**Comment by tonglil** [comment]
Completed in https://github.com/drone/docs/pull/279.

Please comment or open another issue if that was not enough :)
