### ISSUE TITLE
Privileged mode example has incorrect hostname

### ISSUE THREAD

**Issue by Sharsie** [drone/docs#327]
http://docs.drone.io/privileged-mode/
Hi there, I tried the example snippet in the above documentation page, but connecting to 0.0.0.0:2375 was not possible. Defining the service name instead worked however.

```diff
pipeline:
  build:
    image: docker
    environment:
-      - DOCKER_HOST=tcp://0.0.0.0:2375
+      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker --tls=false ps

services:
  docker:
    image: docker:dind
    command: [ "--storage-driver=vfs", "--tls=false" ]
    privileged: true
```

**Comment by tboerger** [comment]
Instead of writing out this issue you could provide a pull request that resolves that ;)

**Comment by Sharsie** [comment]
Well fine, wasn't sure if this is a general problem or something that has to do with the configuration of the drone server I was testing this on
