### ISSUE TITLE
Broken link on - http://readme.drone.io/0.4/community/contributors_guide/   >>  "Tips, Tricks, and How-To’s"

### ISSUE THREAD

**Issue by darshandeshmukh11** [drone/docs#338]
![image](https://user-images.githubusercontent.com/7932274/39081871-c9a083ae-4566-11e8-917e-68ffc8fee10a.png)

Redirects to - https://discuss.drone.io/c/how-tos

**Comment by tphoney** [comment]
Docs have moved to https://github.com/drone/docs. this no longer is an issue
