### ISSUE TITLE
CLI Doc Suggestions

### ISSUE THREAD

**Issue by 0x123123123** [drone/docs#339]
While trying to use this documentation to run `drone deploy` using `drone` 0.8.5 and drone 6 on the server, I've noticed:
- There are no docs for varying versions of the CLI/server
- The docs are simply the output of `drone deploy --help`
  - This would be fine, but the help docs:
    - Don't show what `[arguments...]` is/means
    - Don't match my version of drone (mine shows the positional arguments for the deploy command, but doesn't explain them)
    - Don't explain common errors. For instance, after following the help output for my version of the `deploy` command, I still see `Error: you must provide the Drone server address.`, and am not sure where to put that. I'm guessing it's either some global config (in which case it should be in the installation page) or a `--param`? Nevermind that seems to be for environment variables. I'm not sure how to specify the drone server address.

**Comment by bradrydzewski** [comment]
> Don't explain common errors.

this would imply you are missing the `DRONE_SERVER` environment variable. The use of this variable is described in the CLI instructions http://docs.drone.io/cli-authentication/, you can also google the error if you need more resources to resolve.

> There are no docs for varying versions of the CLI/server

This is something we will provide when Drone reaches 1.0 and is no longer in beta.

> Don't show what [arguments...] is/means

The reference to `[arguments...]` is automatically generated by the `urfave/cli` library that we are using for command flag parsing. Arguments refers to command-specific arguments and flags, which you can see by running `drone [command] -h`, for example `drone deploy -h`

**Comment by tboerger** [comment]
Beside that, if you execute `drone --help` you will see the required global flags like `--server` and `--token`.
