### ISSUE TITLE
Add HTTPS to docs.drone.io

### ISSUE THREAD

**Issue by sofixa** [drone/docs#356]
Hi there,

I noticed the drone docs aren't served over HTTPS, which:

* Google dislikes, so it's bad for SEO

* Chrome and (soon i think?) Firefox show a "Not secure" next to the URL which can be off putting

From what i've seen (the .drone.yaml file in the repository and dig), the site sits on an S3 bucket for static web hosting. I'd recommend (and would gladly help with the setup !) to add a CloudFront CDN distribution in front of it, which would achieve the following advantages:

* free HTTPS certificate that auto-renews itself, so better SEO and image

* caching, so faster load times (not that they're that long)

* geo distribution, so content will be loaded from the closest location to the visitor (better speed and geo redundancy if S3 in us-east-1 is having issues, which has happened like once or twice before)

* costs can be are lower - with S3, you pay $0.09 per GB for data, and with CloudFront it's between $0.020 an $0.160 depending on visitor location (US and Europe are $0.020). Requests are a tad more expensive with CloudFront though (between $0.0100 and $0.0220 per 10,000 HTTPS requests depending on visitor location for CloudFront vs $0.004 per 10,000 requests for S3)

Cheers,
Adrian

**Comment by bradrydzewski** [comment]
We host the Blog and autoscaler docs to Netlify and are planning to move the Drone docs to Netlify in the coming weeks. The move to Netlify will coincide with our 0.9 release, which will require a lot of documentation updates.
