### ISSUE TITLE
Migrate documentation from Markdown to AsciiDoc

### ISSUE THREAD

**Issue by settermjd** [drone/docs#369]
This might seem like a trivial thing to do, but [AsciiDoc](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/) is one of the few file formats that was specifically designed for writing technical documentation. The other leading contender is [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText) (with or without [the Sphinx-Doc extensions](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)). 

[Markdown](https://en.wikipedia.org/wiki/Markdown), despite it's signifcant industry support however, was only designed as a lightweight markup format, originally for writing basic HTML files. AsciiDoc on the other hand has a wealth of functionality specifically for the use case that is highly detailed technical documentation.

It has support for much needed features, such as _admonitions,_ _complex tables and lists_, _macros,_ _attributions_, _substitutions,_ _text replacement_, _configurable table of contents_, _bibliographies,_ and _footnotes,_. Along with the Asciidoctor toolchain, the format is able to be exported to a range of other formats, such as _PDF,_ _ePUB,_ _Mobi,_ and more!

How would the documentation be migrated? There should only be a minimum of effort required, as [Pandoc](https://pandoc.org/) can do the majority of the work.

**Comment by bradrydzewski** [comment]
Hugo supports extensions to your markdown documents using custom tags, called shortcodes https://gohugo.io/content-management/shortcodes/

For an admonitions you could create a `shortcodes/alert.html` file:

```
<div class="alert">{{ Inner }}</div>
```

And then use the shortcode in our markdown document like this:

```
{{< alert >}}
Write your custom warning text here
{{< / alert >}}
```

**Comment by tboerger** [comment]
Maybe we should consider to build the docs with antora instead of Hugo? We are currently introducing that to owncloud. It got native support for different versions and it can also fetch docs from different repos

**Comment by bradrydzewski** [comment]
Unfortunately moving away from Hugo is not an option at this time. If we started from scratch (with a new tool) and had to re-create all of our templates and structure, we could end up blowing through the entire budget before any new documentation is written. So given the limited time and budget, I think we should focus on the major problem areas (installation docs, etc) as opposed to tooling.

**Comment by tboerger** [comment]
Ok, got it and totally fine by me. Just wanted to mention that since Antora was built from the ground up for documentation pages :)

**Comment by tphoney** [comment]
This does not look like we are going to implement this.
