### ISSUE TITLE
Integrate Account Signup into the Documentation

### ISSUE THREAD

**Issue by settermjd** [drone/docs#373]
Similar to [the Stripe docs](https://stripe.com/docs), integrating an account signup link universally throughout the documentation should be included. 

![bildschirmfoto 2018-10-05 um 14 38 44](https://user-images.githubusercontent.com/196801/46535645-663cf080-c8ac-11e8-95c9-bd3924ac5c56.png)

This is because every user comes to the docs for a different reason. Some may be existing users who are trying to perform a certain task. Some may be new users just getting a feel for where to begin and how to do basic tasks. And still others may be researching Drone to try and find out what it is and if it's the right fit for their project or organisation. 

It's essential to provide this third user the opportunity to sign-up if they find that Drone is what they're looking for.

**Comment by tboerger** [comment]
But so far drone is mostly an on-premise solution, the SaaS solution is not finished yet. I think this makes sense for SaaS projects only.

**Comment by bradrydzewski** [comment]
>  Some may be new users just getting a feel for where to begin and how to do basic tasks. And still others may be researching Drone to try and find out what it is and if it's the right fit for their project or organisation.

Stripe is a central service (at stripe.com) so a login makes sense. Drone, however, is a self-hosted solution. This means there is no central place for Drone users to login-to, since each Drone user is hosting their own instance on their owns servers.
