### ISSUE TITLE
Integrate a "Questions" Section Into Every Documentation Page Footer

### ISSUE THREAD

**Issue by settermjd** [drone/docs#374]
I think that this is an excellent feature, one that should definitely be continued and extended to every page of the documentation. There will always be users who have trouble or don't quite understand something at first. This can be for any number of reasons, such as a lack of background knowledge, and a lack of overall technical experience. There should always be a way for them to get help when they need it.

**Comment by bradrydzewski** [comment]
also we have this on the new docs (at readme.drone.io)

<img width="415" alt="screen shot 2018-10-05 at 9 43 31 am" src="https://user-images.githubusercontent.com/817538/46548207-35949100-c883-11e8-93d5-63d74ff7fee0.png">

**Comment by tphoney** [comment]
This is imlpemented 
![image](https://user-images.githubusercontent.com/10402706/124594307-8e8c1c00-de57-11eb-98a1-6581ee94c80b.png)
