### ISSUE TITLE
Typos in Docs

### ISSUE THREAD

**Issue by douglasmiranda** [drone/docs#383]
just the word "intsance", I think you meant "instance"

```
node:
  intsance: highmem
```

https://docs.drone.io/config/pipeline/nodes/

**Comment by douglasmiranda** [comment]
Another typo in Pipeline > Services.

"paramters"

https://docs.drone.io/config/pipeline/services/

(Commenting here, in order to not flood with "typo issues")

**Comment by douglasmiranda** [comment]
In Pipeline > Services > Detached Steps:

I think it should be: `- redis-cli -h redis ping` instead of `- redis-cli -h cache ping`

**Comment by douglasmiranda** [comment]
Pipeline > Services > Incorrect Hostname

"It is import to remember"

probably should be:

"It is important to remember"

**Comment by tcardonne** [comment]
Hi,

I'm pretty sure there is also a small typo in these paragraphs : 
https://docs.drone.io/intro/github/single-machine/#create-an-oauth-application
https://docs.drone.io/intro/gitlab/single-machine/#create-an-oauth-application

For the GitHub page, the following part

> The Consumer Key and Consumer Secret are used to authorize access to Bitbucket resources.

should (at least I guess) be

> The Client ID and Client Secret are used to authorize access to GitHub resources.

**Comment by tphoney** [comment]
The layout of the documentation has changed substantially since this issue was raised. I am closing it for now. You can also submit PR's for changes clicking the link at the bottom of every page.
![image](https://user-images.githubusercontent.com/10402706/124594605-e62a8780-de57-11eb-880d-52b2a0410c8b.png)
