### ISSUE TITLE
Error in Create Secret API Call....

### ISSUE THREAD

**Issue by eprparadocs** [drone/docs#384]
It turns out the API call to Create A Secret shows a request body with name, value and event (lower case). In fact it is  Name, Value and Events!

**Comment by tphoney** [comment]
![image](https://user-images.githubusercontent.com/10402706/124594733-0e19eb00-de58-11eb-8407-62d2e175b04a.png)
Can you link to the page, or make the change on the page, as i cannot find this.
Sorry.
