### ISSUE TITLE
Slight modification needed for R config

### ISSUE THREAD

**Issue by tyluRp** [drone/docs#386]
See this [page](https://docs.drone.io/samples/languages/r/). Specifically the line:

```
- R -e 'install.package(c("package1","package2"))'
```

Needs to be changed to:

```
- R -e 'install.packages(c("package1","package2"))'
```

That is, use `install.packages` instead of `install.package` because the latter doesn't exist. If unchanged, the user will get an error as seen [here](https://cloud.drone.io/tyluRp/treeco/3/1/2)

**Comment by tphoney** [comment]
This is fixed https://docs.drone.io/pipeline/kubernetes/examples/language/r/
