### ISSUE TITLE
support jsonnet yaml imports

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#387]
this will track the ability to import yaml files. This could (for example) be used by mono-repositories where each subdirectory has a configuration file. Ideally each subdirectory would have a configuration file defined in jsonnet, but some teams may prefer yaml.

```
local parseYaml = std.native("parseYaml");

[
  parseYaml(importstr "subdir1/.drone.yml")[0],
  parseYaml(importstr "subdir2/.drone.yml")[0],
  parseYaml(importstr "subdir3/.drone.yml")[0],
]
```

this could probably be improved by differentiating between `parseYaml` (single doc) and `parseYamlStream` (multi-doc). The above version always returns a multi-document yaml, hence the reason we have to use `[0]`

**Comment by tphoney** [comment]
this is pretty old, closing
