### ISSUE TITLE
Docs error on github installation

### ISSUE THREAD

**Issue by leiserfg** [drone/docs#388]
https://docs.drone.io/installation/github/single-machine/
sais Bitbucket resources instead of Github resources

**Comment by jnaulty** [comment]
I'm unable to find this page in the drone/docs repo :confused: 
![image](https://user-images.githubusercontent.com/6826729/55353956-5bd56b00-5479-11e9-8ecb-9a598d439f1c.png)

even `git grep 'Prerequisites'` is coming up empty.

even searching through the github GUI is not yielding results from under the "Prerequisites" header:
https://github.com/drone/docs/search?q=he+Consumer+Key+and+Consumer+Secret+are+used+to+authorize+access+to&unscoped_q=he+Consumer+Key+and+Consumer+Secret+are+used+to+authorize+access+to

**Comment by chihkaiyu** [comment]
This also happens on GitLab installation.

![wrong_scm](https://user-images.githubusercontent.com/8611874/57078527-0531aa00-6d21-11e9-84df-23cdad57ca80.png)

**Comment by tphoney** [comment]
These typo's are now fixed. thanks for raising the issue
