### ISSUE TITLE
Missing workspace documentation

### ISSUE THREAD

**Issue by clandmeter** [drone/docs#391]
I cannot find workspace documentation in the 1.0.0 docs.

**Comment by tboerger** [comment]
So far it's only documented within the golang example, we should put an explanation on a better place.

**Comment by MetalBlueberry** [comment]
I've found the same issue for 1.0.0.
As a workaround. I think the [documentation for 0.8.0](https://github.com/drone/docs/blob/master/content/usage/concepts/workspace.md) is valid.

**Comment by tboerger** [comment]
To repeat the statement of @bradrydzewski from Gitter chat, he deprecated the workspace config and considers to drop it in a future version.

**Comment by tphoney** [comment]
Closing this, due to deprecation
