### ISSUE TITLE
1.0.0 Unclear Jsonnet instructions

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/docs#394]
This page describes using Jsonnet to generate matrix-like configurations: https://docs.drone.io/user-guide/pipeline/migrating/

Apparently Drone itself doesn't parse Jsonnet files, but only the drone cli command can convert Jsonnet to Drone manifests (YAML).

I think the documentation is unclear and should mention how to use `drone jsonnet` to generate the `.drone.yml`

**Comment by tphoney** [comment]
This is documented here https://docs.drone.io/cli/drone-jsonnet/
