### ISSUE TITLE
Organization's Drone asking for access to my personal github account

### ISSUE THREAD

**Issue by chrisghill** [drone/docs#396]
I can't find documentation on this so I'm creating an issue here looking for assistance.  We've been running Drone (currently version 0.5) for a few years now.  We've recently adopted Kubernetes so I'm trying to follow the guides to implement Drone 1.0 in Kubernetes.  The server comes up fine, but when I navigate to Drone's web console I'm immediately prompted with a page to authorize Drone to access **my** personal github account.  Here is a screenshot:
![image](https://user-images.githubusercontent.com/15616541/55040781-9d849280-4fef-11e9-95a5-35a35459a508.png)
I've replaced all mentions of the Organization with the phrase "Organization".  But this seems really sketchy.  My intention is for Drone to manage repositories owned by the organization.  Why does drone need access to **my** personal github account?  Plus I don't remember ever having to authorize Drone this way in the past.

Here is my ENV configuration:
```
DRONE_KUBERNETES_ENABLED=true
DRONE_KUBERNETES_NAMESPACE=our-namespace
DRONE_GITHUB_SERVER=https://github.com
DRONE_GITHUB_CLIENT_ID=<redacted>
DRONE_GITHUB_CLIENT_SECRET=<redacted>
DRONE_RPC_SECRET=<redacted>
DRONE_SERVER_HOST=drone.organization.com
DRONE_SERVER_PROTO=https
DRONE_OPEN=true
DRONE_ORGS=Organization
DRONE_GITHUB=true
DRONE_ADMIN=user1,user2,etc
```

Have I misconfigured Drone? Is this standard now?  If so, what justification is there in giving github access to user's personal accounts when it won't be managing those repositories?

**Comment by bradrydzewski** [comment]
👋  hey there, we provide end-user support at [docs.drone.io](https://docs.drone.io) and [gitter.im/drone/drone](https://gitter.im/drone/drone). I can save you some copy / paste and just answer your question here -- this is normal and you definitely would have been presented with this exact same screen years ago when you first logged-into version 0.5.  Drone has always used oauth2 to access GitHub data on your behalf.

**Comment by chrisghill** [comment]
@bradrydzewski okay, I must have just forgotten.  Thank you for your quick reply and the helpful links!

**Comment by bradrydzewski** [comment]
no worries, 2 years is a long time, and it never hurts to ask security-related questions :)
