### ISSUE TITLE
Data volume path is wrong, should be `/data`, not `/var/lib/drone`

### ISSUE THREAD

**Issue by chihkaiyu** [drone/docs#399]
All of the installation guides provide the wrong data volume path: `--volume=/var/lib/drone:/data \`.  

According to the code, it should be at `/data`.   

See https://github.com/drone/drone/blob/master/docker/Dockerfile.server.linux.amd64#L13
(I've also checked it with the image `drone/drone:1.1.0`)  

This repository seems a little behind the [current document site](https://docs.drone.io/) so I don't how to issue a PR.

![drone](https://user-images.githubusercontent.com/8611874/57078065-17f7af00-6d20-11e9-833b-7b33c4863c20.png)

**Comment by bradrydzewski** [comment]
I do not see any issue ... `/var/lib/drone:/data` mounts `/data` in the container [1] to `/var/lib/drone` on the host machine. You can of course change `/var/lib/drone` to be whatever you want, as long as the target path is `/data` in the container.

[1] https://github.com/drone/drone/blob/master/docker/Dockerfile.server.linux.amd64#L13

**Comment by chihkaiyu** [comment]
Ah... I'm so sorry. I messed up with source and destination of docker volumes...
