### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by brandonkal** [drone/docs#401]
There are many dead links in the forums and in the discussions on issues here. If possible, configuring redirects to the new domains and linting documentation for dead links would improve that experience.

**Comment by brandonkal** [comment]
Okay. I will generate a list of all the dead links when I find the cycles to do so and post it here. This will take some time as you say.

**Comment by philoticapps** [comment]
I've also noticed this issue, and I'd like to provide some feedback to the Drone team.

In retrospect, I think it's pretty clear that it was not a wise decision to break most (if not all?) of your previous documentation links.

Perhaps there was a technical reason for this - I don't know.

But I hope you can see why this is a frustrating issue for anyone relying on your documentation or who had ever linked to it prior - StackOverflow, on Github, or even internally like @brandonkal did.

In using Drone for just 2 weeks now, I've run into countless broken Drone docs links across the web.

I don't know what members of the team made this decision. 

But going forward, I would hope that they would incorporate this lesson. Once you've published your documentation, you're responsible for backwards compatibility - at a minimum via redirects, if not through outright versioning.


---

Having said all of that, I also want to express my appreciation for all of the great work the team has done in making an excellent alternative to other CI systems.

One of my favorite aspects of it is how well it competes with paid options like CircleCI.

My team had a need for a self-hosted CI system, and we weren't particularly fond of going down the Jenkins rabbit hole. Drone is proving to be quite nice so far.

Thanks for all of your hard work 🙏

**Comment by ashwilliams1** [comment]
We have over 215 redirects that redirect from old paths to new paths. If there are important redirects we missed please provide examples.  And yes, we understand it is frustrating that there may be dead links out there -- but you do not know the true meaning of frustration until you try and maintain a large open source project. Trust me.

**Comment by bradrydzewski** [comment]
we have been (for some time now) trying to fix broken links. These sort of comments look backward when we are trying to move forward. We do not need a lecture on our mistakes or our responsibilities or whether or not we learned our lesson (seriously??).  If you want to be part of the solution please submit broken links to [this thread](https://discourse.drone.io/t/help-us-redirect-dead-links/6824) and we will happily setup a redirect.
