### ISSUE TITLE
os.GetEnv() is wrong in docs 

### ISSUE THREAD

**Issue by amirbagh75** [drone/docs#405]
https://readme.drone.io/plugins/golang/
change os.GetEnv("") to os.Getenv("")
[i'm using go 1.13]

**Comment by tboerger** [comment]
readme.drone.io is not the current documentation, it will disappear and don't receive any updates.

**Comment by amirbagh75** [comment]
But the same in the original doc:
https://docs.drone.io/plugins/golang/ 
still os.GetEnv("")
