### ISSUE TITLE
Consider an "About" or "Overview" or some other more general section

### ISSUE THREAD

**Issue by gtaylor** [drone/docs#45]
As in another section on the top navbar. This should have general information about Drone, and should also probably contain the whole doc site's landing page. The first thing the users should see when hitting the doc site is an explanation of what drone is, what makes it special, and some sub-sections elaborating on some of the things mentioned.

For the landing page, important questions to answer:

* What is drone?
* What makes it special compared to the alternatives?
* What are some of the most attractive capabilities or attributes?

**Comment by bradrydzewski** [comment]
agreed we need this sort of page, although I see this as a replacement for the content at drone.io. I friend of mine put together try.drone.io a few months back and I think this could be expanded to be more informative. thoughts? we could craft new content for try.drone.io and I could see if he can update the design

**Comment by gtaylor** [comment]
try.drone.io is very useful, but I guess what I'd be looking for is higher-level overviews and general information that go into more depth than try.drone.io does or should. For example:

* Basic architectural diagrams don't fit under "Installation", "Usage", "Plugins", or even "Developers". 
* The history and origins of Drone (why was it created?) is useful information and informs people as to what differentiates us without directly saying "We are better than Jenkins because X".
* While try.drone.io might show a small subset of who is using Drone (maybe at least their logos), we could go into greater detail like here: http://www.sqlalchemy.org/organizations.html
* Key features could be outlined in greater detail than try.drone.io (http://www.sqlalchemy.org/features.html)
* If we wanted to render a changelog, that'd probably be more general than developer.

There would be some overlap with the marketing site, but that's perfectly fine. We may even want to link some of the points on the marketing site to the more in-depth sections in the docs.

Does that make any sense?

**Comment by bradrydzewski** [comment]
Some thoughts

> Basic architectural diagrams don't fit under "Installation", "Usage", "Plugins", or even "Developers".

agreed this doesn't fit on a marketing site.

> Key features could be outlined in greater detail than try.drone.io 

I see this as a subset of the marketing page similar to http://www.weebly.com/features

> While try.drone.io might show a small subset of who is using Drone (maybe at least their logos), we could go into greater detail like here

I think this would be very nice but could also be part of a marketing site

> If we wanted to render a changelog, that'd probably be more general than developer.

I'd like to start using GitHub releases for this sort of thing. I think we could put a link from the proposed community page

> The history and origins of Drone (why was it created?) is useful information and informs people as to what differentiates us without directly saying "We are better than Jenkins because X".

This sounds like a good "about" page on the marketing site

**Comment by gtaylor** [comment]
It's not quite yet done yet, but the Introduction page in the branch will satisfy this.
