### ISSUE TITLE
"keyb" repeated twice, should be "keya" first time

### ISSUE THREAD

**Issue by escote-tatari** [drone/docs#452]
```
 sidler@home  ~/repos/drone/docs   master  rg keyb
content/extensions/environment.md
119:    "name": "keyb",
124:    "name": "keyb",
```
"keyb" repeated twice; should be "keya". Attempted to create PR, denied.

**Comment by tphoney** [comment]
Thanks @escote-tatari https://github.com/drone/docs/blob/master/content/extensions/environment.md has been updated
