### ISSUE TITLE
Missing documentation info about commands

### ISSUE THREAD

**Issue by o2themar** [drone/docs#480]
After testing my build using commands I noticed that when it is included it overrides the dockerfile. However, when I remove it the dockerfile runs as normal. If this is the expected behavior then this should be documented under the commands section below so people know this is the expected behavior. *Note this is just one place where commands is mentioned. There are multiple places where the same definition for commands is mentioned so it should be updated in the other places as well.

https://docs.drone.io/pipeline/kubernetes/syntax/steps/#:~:text=install%0A%20%20-%20npm%20test-,Commands,-The%20commands%20are

**Comment by tphoney** [comment]
Hey @o2themar it does explain it, its just a little further down. Note 

```
The above shell script is then executed as the docker entrypoint.
```

**Comment by o2themar** [comment]
@tphoney I see it now. The wording must have thrown me off. It should mention overriding the entrypoint to make it more clear.

**Comment by tphoney** [comment]
i can emphasise that line, mark it in bold.

**Comment by tphoney** [comment]
updated
