### ISSUE TITLE
Inconsistency of the highlight in example limits pipeline execution on Macstadium's configuration trigger by action 

### ISSUE THREAD

**Issue by adiati98** [drone/docs#511]
To keep the consistency throughout the docs, we need to update the below example limits pipeline execution by action to be highlighted and be consistent with the rest.

![macstadium-trigger-by-action](https://user-images.githubusercontent.com/45172775/139339949-b62ca406-c119-4403-88d9-5480eeb3f1ba.jpg)

**Comment by tphoney** [comment]
Hi @adiati98 did you create a pr for this ?

**Comment by adiati98** [comment]
Hey @tphoney 
Yes, I did. 

It's https://github.com/drone/docs/pull/512

**Comment by tphoney** [comment]
we can close this then 😄 

thanks 👍
