### ISSUE TITLE
Community guide build failure

### ISSUE THREAD

**Issue by gtaylor** [drone/docs#67]
@bradrydzewski this is a bit baffling, but it looks like the S3 upload of the Contributors Guide is failing: http://beta.drone.io/drone/docs/35
```
ERROR: failed to upload /drone/src/github.com/drone/docs/public/community/contributors_guide/index.html to community/contributors_guide/index.html: : 
	status code: 404, request id: 
[info] build failed (exit code 1)
```
Everything builds fine locally, and even during the run it doesn't look like there are any errors until we attempt to upload.

**Comment by gtaylor** [comment]
@bradrydzewski Hate to pester you, but this one is troublesome for our docs. If you have any ideas, I'm all ears.

**Comment by bradrydzewski** [comment]
@gtaylor I actually encountered the same error a few days ago and logged https://github.com/drone-plugins/drone-s3-sync/issues/4

**Comment by gtaylor** [comment]
Ahh, I missed that. Too weird. I might try to find some time to poke at this soon.

**Comment by gtaylor** [comment]
Sounds like this was fixed recently in the S3 sync plugin. Woohoo!
