### ISSUE TITLE
Add Commonly Proposed section

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#72]
we should add a commonly proposed / rejected section to the docs similar to:
https://github.com/apple/swift-evolution/blob/master/commonly_proposed.md

this will be useful to point people to when they ask for something that is considered out of scope for the Drone project and should be implemented externally, such as artifacts, coverage, test reporting, etc

**Comment by gtaylor** [comment]
I added a feature request section here: https://github.com/drone/docs/blob/release/0.5/content/support/help.md

Does this satisfy the general spirit of this issue?
