### ISSUE TITLE
add browser section to docs

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#76]
We should add a section (probably an entire page) for browser testing. This should include local selenium testing using the default chrome and firefox selenium images from DockerHub (example at https://github.com/drone-demos/drone-go-selenium/blob/chrome-and-firefox/.drone.yml) and Sauce Labs instructions as well

**Comment by gtaylor** [comment]
I'm thinking that this could be a repo under drone-demos which we can link to from the docs.

**Comment by bradrydzewski** [comment]
we can probably close this because I've since added a sample yaml to the 0.5 docs
http://readme.drone.io/0.5/usage/samples/#selenium:8c9c32f4cae83233cf5269e0aaec64bb

and added demo projects to the drone-demos org:

* chrome: https://github.com/drone-demos/drone-go-selenium
* chrome and firefox: https://github.com/drone-demos/drone-go-selenium/tree/chrome-and-firefox
