### ISSUE TITLE
No menu on iOS

### ISSUE THREAD

**Issue by AlekSi** [drone/docs#77]
iPad mini, iOS 9.2.1, portrait orientation. Works on landscape orientation.

![img_0080](https://cloud.githubusercontent.com/assets/11512/12625286/31f15140-c544-11e5-9451-c5054c067e55.JPG)

**Comment by tboerger** [comment]
We have to improve the standard theme of all drone pages related to responsive UIs

**Comment by gtaylor** [comment]
Site template is completely changed for 0.5, so this should be good http://readme.drone.io/0.5/usage/overview/
