### ISSUE TITLE
Questions setting up github

### ISSUE THREAD

**Issue by tleyden** [drone/docs#98]
I'm going over [this page on setting up github](https://github.com/drone/docs/blob/master/content/setup/remotes/github.md), and have some questions.  I managed to figure out that to get a `client_id` and `client_secret`, I need to [register](https://github.com/settings/applications/new) a new Oauth application on github.

However, I'm looking at this screen:

<img width="740" alt="screen shot 2016-02-15 at 12 06 18 pm" src="https://cloud.githubusercontent.com/assets/296876/13059075/8c81dff2-d3dc-11e5-9d42-881fee1d2565.png">

And not sure what to fill out for the **Authorization callback URL**.  (or for that matter, the **Homepage URL**).  At the moment I'm trying to setup a self-hosted drone on an anonymous EC2 instance under docker.

Any help would be appreciated and I'd be happy to follow up with a PR on the docs.

**Comment by gtaylor** [comment]
Check the end of the release/0.5 github reference for details: https://github.com/drone/docs/blob/release/0.5/content/installation/services/github.md

Homepage URL is kind of an arbitrary thing that is shown in the Github user's list of authorized apps. It should point to the root URI for your Drone install.
